# Docker Compose - Orchestrates the Calyptia Fluentd container
# Usage:
#   Development: ENV=dev docker compose up
#   Production:  ENV=prod docker compose up

services:
  fluentd:
    # Build from our local Dockerfile with environment-specific config
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV:-dev}
        DASH0_API_KEY: ${DASH0_API_KEY}
        DASH0_DATASET: ${DASH0_DATASET}
        DASH0_LOGS_ENDPOINT: ${DASH0_LOGS_ENDPOINT}
    
    # Container name for easy reference
    container_name: fluentd-${ENV:-local-dev}
    
    # Port mapping: host:container
    ports:
      - "8888:8888"   # HTTP input endpoint
      - "24220:24220" # Monitoring endpoint
    
    # Load environment variables from local env file
    env_file:
      - .env.${ENV:-local-dev}
    
    # Override specific environment variables if needed
    environment:
      - ENV=${ENV:-dev}
    
    # Restart policy for reliability
    restart: unless-stopped
    
    # Network configuration
    networks:
      - fluentd-network

networks:
  fluentd-network:
    driver: bridge