# Docker Compose - Development Environment
services:
  fluentd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=dev
    
    container_name: calyptia-fluentd-dev
    
    ports:
      - "8888:8888"   # HTTP input endpoint
      - "24220:24220" # Monitoring endpoint
    
    restart: unless-stopped
    
    networks:
      - fluentd-network

networks:
  fluentd-network:
    driver: bridge