[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/plugins.json"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables
[deploy.environmentVariables]
NODE_ENV = "production"
SERVICE_NAME = "fluentd-aggregator"

# Railway will provide these via secrets
# DASH0_API_KEY = "auth_..."
# DASH0_DATASET = "production"
# REDIS_HOST = "..."
# REDIS_PASSWORD = "..."
# FLUENTD_SHARED_KEY = "..."

[build.env]
RUBY_VERSION = "3.1"