/**
 * Hybrid Machine Service Environment Interface
 * Container supporting both GPU workloads (ComfyUI) and API workloads (OpenAI, Replicate, etc.)
 */

export const HybridMachineEnvInterface = {
  name: "hybrid_machine",
  location: "apps/machine",
  file_name: ".env.hybrid",
  
  required: {
    // Redis connection (used by both machine and workers)
    "HUB_REDIS_URL": "REDIS_URL",

    // Machine identity and Redis connection
    "MACHINE_ID": "HYBRID-MACHINE_ID",
    "MACHINE_CONTAINER_NAME": "HYBRID-MACHINE_ID",

    // Expose Ports
    "MACHINE_EXPOSE_PORTS": "HYBRID-MACHINE_EXPOSE_PORTS",

    // Has GPU (hybrid machines typically have GPU)
    "MACHINE_HAS_GPU": "HYBRID-MACHINE_HAS_GPU",
    
    // Machine service enablement flags
    "MACHINE_ENABLE_COMFYUI": "HYBRID-MACHINE_ENABLE_COMFYUI",
    "MACHINE_ENABLE_API": "HYBRID-MACHINE_ENABLE_API",
    "MACHINE_ENABLE_REDIS_WORKERS": "HYBRID-MACHINE_ENABLE_REDIS_WORKERS",
    "MACHINE_ENABLE_SIMULATION": "HYBRID-MACHINE_ENABLE_SIMULATION",
    "MACHINE_ENABLE_NGINX": "HYBRID-MACHINE_ENABLE_NGINX",
    "MACHINE_ENABLE_A1111": "HYBRID-MACHINE_ENABLE_A1111", 
    "MACHINE_ENABLE_OLLAMA": "HYBRID-MACHINE_ENABLE_OLLAMA",

    // Performance & Resource Limits
    "WORKER_RAM_GB": "HYBRID-MACHINE_RAM_GB",
    "WORKER_MAX_CONCURRENT_JOBS": "HYBRID-MACHINE_MAX_CONCURRENT_JOBS",
    "WORKER_JOB_TIMEOUT_MINUTES": "HYBRID-MACHINE_JOB_TIMEOUT_MINUTES",

    // PM2 Service Management
    "PM2_HOME": "MACHINE_PM2_HOME",
    "MACHINE_STATUS_UPDATE_INTERVAL_SECONDS": "MACHINE_STATUS_UPDATE_INTERVAL_SECONDS",

    // Credentials
    "MACHINE_HF_TOKEN": "API-TOKENS_HF_TOKEN",
    "MACHINE_CIVITAI_TOKEN": "API-TOKENS_CIVITAI_TOKEN",
    "MACHINE_OPENAI_API_TOKEN": "API-TOKENS_OPENAI_API_KEY",
    "MACHINE_REPLICATE_API_TOKEN": "API-TOKENS_REPLICATE_API_TOKEN",
    "MACHINE_OLLAMA_PORT": "OLLAMA_PORT",
    "MACHINE_OLLAMA_HOST": "OLLAMA_HOST",
    "MACHINE_CLOUD_CDN_URL": "STORAGE-PROVIDER_CDN_URL",
    "MACHINE_AWS_ACCESS_KEY_ID": "STORAGE-PROVIDER_AWS_ACCESS_KEY_ID",
    "MACHINE_AWS_SECRET_ACCESS_KEY_ENCODED": "STORAGE-PROVIDER_AWS_SECRET_ACCESS_KEY_ENCODED",
    "MACHINE_AWS_DEFAULT_REGION": "STORAGE-PROVIDER_AWS_DEFAULT_REGION",
    "MACHINE_GOOGLE_APPLICATION_CREDENTIALS": "STORAGE-PROVIDER_GOOGLE_APPLICATION_CREDENTIALS",
    "MACHINE_AZURE_STORAGE_ACCOUNT": "STORAGE-PROVIDER_AZURE_STORAGE_ACCOUNT",
    "MACHINE_AZURE_STORAGE_KEY": "STORAGE-PROVIDER_AZURE_KEY",
    "MACHINE_CLOUD_PROVIDER": "STORAGE-PROVIDER_CURRENT_PROVIDER",
    "MACHINE_CLOUD_STORAGE_CONTAINER": "STORAGE-PROVIDER_CONTAINER",

    // Worker ComfyUI connection (uses values from ComfyUI component)
    "WORKER_COMFYUI_REMOTE": "COMFYUI_REMOTE",
    "WORKER_COMFYUI_HOST": "COMFYUI_HOST",
    "WORKER_COMFYUI_PORT": "COMFYUI_BASE_PORT",
    "WORKER_COMFYUI_USERNAME": "COMFYUI_USERNAME",
    "WORKER_COMFYUI_PASSWORD": "COMFYUI_PASSWORD",
  },
  
  optional: {
    // Machine hardware configuration
    "MACHINE_NUM_GPUS": "HYBRID-MACHINE_NUM_GPUS",
    "MACHINE_GPU_MEMORY_GB": "HYBRID-MACHINE_GPU_MEMORY_GB",
    "MACHINE_GPU_MODEL": "HYBRID-MACHINE_GPU_MODEL",
    
    // CUDA configuration
    "CUDA_VISIBLE_DEVICES": "HYBRID-MACHINE_CUDA_VISIBLE_DEVICES",
    "GPU_ID": "HYBRID-MACHINE_GPU_ID",
    
    // Machine monitoring and health
    "MACHINE_HEALTH_PORT": "HYBRID-MACHINE_HEALTH_PORT",
    "MACHINE_LOG_LEVEL": "HYBRID-MACHINE_LOG_LEVEL",
    "MACHINE_TEST_MODE": "HYBRID-MACHINE_TEST_MODE",

    // Worker performance tuning
    "WORKER_MAX_BATCH_SIZE": "HYBRID-MACHINE_MAX_BATCH_SIZE",
    "WORKER_MEMORY_CONSTRAINED": "HYBRID-MACHINE_MEMORY_CONSTRAINED",
    "WORKER_PERFORMANCE_TIER": "HYBRID-MACHINE_PERFORMANCE_TIER",

    // Worker heartbeat & communication
    "WORKER_HEARTBEAT_INTERVAL": "MACHINE_HEARTBEAT_INTERVAL",
    "WORKER_HEARTBEAT_TIMEOUT_SEC": "MACHINE_HEARTBEAT_TIMEOUT_SEC",
    "WORKER_POLL_INTERVAL_MS": "MACHINE_POLL_INTERVAL_MS",
    "WORKER_WEBSOCKET_RECONNECT_DELAY_MS": "MACHINE_WEBSOCKET_RECONNECT_DELAY_MS",
    "WORKER_WEBSOCKET_MAX_RECONNECT_ATTEMPTS": "MACHINE_WEBSOCKET_MAX_RECONNECT_ATTEMPTS",

    // Worker authentication and security
    "WORKER_WEBSOCKET_AUTH_TOKEN": "REDIS_PASSWORD",

    // Service port configuration
    "COMFYUI_BASE_PORT": "HYBRID-MACHINE_COMFYUI_BASE_PORT",
    "A1111_BASE_PORT": "HYBRID-MACHINE_A1111_BASE_PORT",
    "OLLAMA_PORT": "HYBRID-MACHINE_OLLAMA_PORT",

    // Development & Debug
    "WORKER_DASHBOARD_ENABLED": "MACHINE_DASHBOARD_ENABLED",
    "WORKER_DASHBOARD_PORT": "MACHINE_DASHBOARD_PORT",
    "WORKER_DEBUGGING_ENABLED": "MACHINE_DEBUGGING_ENABLED",
    "WORKER_DEVELOPMENT_MODE": "MACHINE_DEVELOPMENT_MODE",
    "DISABLE_FILE_LOGGING": "MACHINE_DISABLE_FILE_LOGGING",

    // API Worker Configuration
    "MACHINE_API_WORKER_COUNT": "HYBRID-MACHINE_API_WORKER_COUNT",
    "API_WORKER_CONNECTORS": "HYBRID-MACHINE_API_WORKER_CONNECTORS",

    // Deployment environment
    "NODE_ENV": "DEPLOYMENT_NODE_ENV",
    "CUSTOMER_ISOLATION": "PLATFORM_CUSTOMER_ISOLATION",

    // Custom ComfyUI Nodes Environment Variables (unprefixed - what the nodes expect)
    "AWS_ACCESS_KEY_ID": "STORAGE-PROVIDER_AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY_ENCODED": "STORAGE-PROVIDER_AWS_SECRET_ACCESS_KEY_ENCODED",
    "AWS_DEFAULT_REGION": "STORAGE-PROVIDER_AWS_DEFAULT_REGION",
    "GOOGLE_APPLICATION_CREDENTIALS": "STORAGE-PROVIDER_GOOGLE_APPLICATION_CREDENTIALS",
    "AZURE_STORAGE_ACCOUNT": "STORAGE-PROVIDER_AZURE_STORAGE_ACCOUNT", 
    "AZURE_STORAGE_KEY": "STORAGE-PROVIDER_AZURE_KEY",
    "CLOUD_PROVIDER": "STORAGE-PROVIDER_CURRENT_PROVIDER",
    "CLOUD_STORAGE_CONTAINER": "STORAGE-PROVIDER_CONTAINER",
    "CLOUD_CDN_URL": "STORAGE-PROVIDER_CDN_URL",
    "HF_TOKEN": "API-TOKENS_HF_TOKEN",
    "CIVITAI_TOKEN": "API-TOKENS_CIVITAI_TOKEN",
    "OPENAI_API_KEY": "API-TOKENS_OPENAI_API_KEY",
    "OLLAMA_HOST": "OLLAMA_HOST",
    "OLLAMA_PORT": "OLLAMA_PORT",
    "OLLAMA_DEFAULT_MODEL": "OLLAMA_DEFAULT_MODEL",
    "EMPROPS_DEBUG_LOGGING": "EMPROPS_DEBUG_LOGGING",
    "STATIC_MODELS": "STATIC_MODELS",
  },
  
  defaults: {
    "WORKER_CONNECTORS": "simulation, comfyui, openai, replicate",
    "MACHINE_TYPE": "hybrid",
    "MACHINE_HAS_GPU": "true"
  }
};