/**
 * Machine Service Environment Interface
 * Container orchestration and service management
 */

export const MachineEnvInterface = {
  name: "machine",
  location: "apps/machine",
  
  required: {
    // Redis connection (used by both machine and workers)
    "HUB_REDIS_URL": "REDIS_URL",

    "WORKER_BUNDLE_MODE": "WORKER_BUNDLE_MODE",

    "UNIFIED_MACHINE_STATUS":"WORKER_UNIFIED_MACHINE_STATUS",

  },
  
  optional: {
    
    // Machine monitoring and health
    "MACHINE_HEALTH_PORT": "MACHINE_HEALTH_PORT",
    "MACHINE_LOG_LEVEL": "MACHINE_LOG_LEVEL",
    "EXPOSE_PORTS":"MACHINE_EXPOSE_PORTS",

    // Worker authentication and security
    "WORKER_WEBSOCKET_AUTH_TOKEN": "REDIS_PASSWORD",

    // Remote ComfyUI
    "WORKER_COMFYUI_REMOTE_TIMEOUT_SECONDS":"COMFYUI_REMOTE_TIMEOUT_SECONDS",
    "WORKER_COMFYUI_REMOTE_MAX_CONCURRENT_JOBS":"COMFYUI_RETRY_DELAY_SECONDS",

    // Custom ComfyUI Nodes Environment Variables (unprefixed - what the nodes expect)

    "STATIC_MODELS": "STATIC_MODELS",

    "COMFYUI_EXPOSE_PORTS":"COMFYUI_EXPOSE_PORTS",
    "COMFYUI_EXPOSED_HOST_PORT_BASE":"COMFYUI_EXPOSED_HOST_PORT_BASE",
    "COMFYUI_EXPOSED_CONTAINER_PORT_BASE":"COMFYUI_EXPOSED_CONTAINER_PORT_BASE",

    "COMFYUI_RESOURCE_BINDING": "COMFYUI_RESOURCE_BINDING",
    "OPENAI_IMAGE_MODEL": "OPENAI_IMAGE_MODEL"
  },

  secret : {
    "AWS_ACCESS_KEY_ID": "STORAGE_PROVIDER_AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY_ENCODED": "STORAGE_PROVIDER_AWS_SECRET_ACCESS_KEY_ENCODED",
    "AWS_DEFAULT_REGION": "STORAGE_PROVIDER_AWS_DEFAULT_REGION",
    "AZURE_STORAGE_ACCOUNT": "STORAGE_PROVIDER_AZURE_STORAGE_ACCOUNT", 
    "AZURE_STORAGE_KEY": "STORAGE_PROVIDER_AZURE_KEY",
    "CLOUD_PROVIDER": "STORAGE_PROVIDER_CURRENT_SERVICE",
    "CLOUD_STORAGE_PROVIDER": "STORAGE_PROVIDER_CURRENT_SERVICE",
    "CLOUD_STORAGE_CONTAINER": "STORAGE_PROVIDER_CONTAINER",
    "CLOUD_CDN_URL": "STORAGE_PROVIDER_CDN_URL",
    "HF_TOKEN": "API_TOKENS_HF_TOKEN",
    "CIVITAI_TOKEN": "API_TOKENS_CIVITAI_TOKEN",
    "OPENAI_API_KEY": "OPENAI_API_KEY",
    "OLLAMA_HOST": "OLLAMA_HOST",
    "OLLAMA_PORT": "OLLAMA_PORT",
    "OLLAMA_DEFAULT_MODEL": "OLLAMA_DEFAULT_MODEL",
    "EMPROPS_DEBUG_LOGGING": "EMPROPS_DEBUG_LOGGING",
    "WORKER_COMFYUI_REMOTE_HOST":"COMFYUI_REMOTE_HOST",
    "WORKER_COMFYUI_REMOTE_PORT":"COMFYUI_REMOTE_PORT",
    "WORKER_COMFYUI_REMOTE_USERNAME":"COMFYUI_REMOTE_USER",
    "WORKER_COMFYUI_REMOTE_PASSWORD":"COMFYUI_REMOTE_PASS"
  },
  
  defaults: {
    // Worker configuration (passed to workers)
    "WORKER_MAX_CONCURRENT_JOBS": "1",
    "WORKER_HEALTH_CHECK_INTERVAL": "30"
  }
};