/**
 * Machine Service Environment Interface
 * Container orchestration and service management
 */

export const MachineEnvInterface = {
  name: "machine",
  location: "apps/machine",
  
  required: {
    // Redis connection (used by both machine and workers)
    "HUB_REDIS_URL": "REDIS_URL",

    // Machine identity and Redis connection
    "MACHINE_ID": "MACHINE_ID",
    "MACHINE_CONTAINER_NAME": "MACHINE_ID",
    
    // Machine hardware configuration
    "MACHINE_NUM_GPUS": "SIMULATION_NUM_GPUS",
    "MACHINE_GPU_MEMORY_GB": "SIMULATION_GPU_MEMORY_GB",
    "MACHINE_GPU_MODEL": "SIMULATION_GPU_MODEL",
    
    // Machine service enablement flags
    "MACHINE_ENABLE_COMFYUI": "MACHINE_ENABLE_COMFYUI",
    "MACHINE_ENABLE_REDIS_WORKERS": "MACHINE_ENABLE_REDIS_WORKERS",
    "MACHINE_ENABLE_SIMULATION": "MACHINE_ENABLE_SIMULATION",

    "MACHINE_HF_TOKEN": "API_TOKENS_HF_TOKEN",
    "MACHINE_CIVITAI_TOKEN": "API_TOKENS_CIVITAI_TOKEN",
    "MACHINE_OPENAI_API_TOKEN": "API_TOKENS_OPENAI_API_KEY",
    "MACHINE_OLLAMA_PORT": "OLLAMA_PORT",
    "MACHINE_OLLAMA_HOST": "OLLAMA_HOST",
    "MACHINE_CLOUD_CDN_URL": "STORAGE_PROVIDER_CDN_URL",
    "MACHINE_AWS_ACCESS_KEY_ID": "STORAGE_PROVIDER_AWS_ACCESS_KEY_ID",
    "MACHINE_AWS_SECRET_ACCESS_KEY_ENCODED": "STORAGE_PROVIDER_AWS_SECRET_ACCESS_KEY_ENCODED",
    "MACHINE_AWS_DEFAULT_REGION": "STORAGE_PROVIDER_AWS_DEFAULT_REGION",
    "MACHINE_GOOGLE_APPLICATION_CREDENTIALS": "STORAGE_PROVIDER_GOOGLE_APPLICATION_CREDENTIALS",
    "MACHINE_AZURE_STORAGE_ACCOUNT": "STORAGE_PROVIDER_AZURE_STORAGE_ACCOUNT",
    "MACHINE_AZURE_STORAGE_KEY": "STORAGE_PROVIDER_AZURE_KEY",
    "MACHINE_CLOUD_PROVIDER": "STORAGE_PROVIDER_CURRENT_PROVIDER",
    "MACHINE_CLOUD_STORAGE_CONTAINER": "STORAGE_PROVIDER_CONTAINER",
    
    // Worker configuration (passed to workers)
    "WORKER_CONNECTORS": "WORKER_CONNECTORS",

    // Worker ComfyUI connection (uses values from ComfyUI component)
    "WORKER_COMFYUI_REMOTE": "COMFYUI_REMOTE",
    "WORKER_COMFYUI_HOST": "COMFYUI_HOST",
    "WORKER_COMFYUI_PORT": "COMFYUI_BASE_PORT",
    "WORKER_COMFYUI_USERNAME": "COMFYUI_USERNAME",
    "WORKER_COMFYUI_PASSWORD": "COMFYUI_PASSWORD",
  },
  
  optional: {
    // Machine service flags
    "MACHINE_ENABLE_NGINX": "MACHINE_ENABLE_NGINX",
    "MACHINE_ENABLE_A1111": "MACHINE_ENABLE_A1111", 
    "MACHINE_ENABLE_OLLAMA": "MACHINE_ENABLE_OLLAMA",
    
    // Machine monitoring and health
    "MACHINE_HEALTH_PORT": "MACHINE_HEALTH_PORT",
    "MACHINE_LOG_LEVEL": "MACHINE_LOG_LEVEL",
    "MACHINE_TEST_MODE": "MACHINE_TEST_MODE",

    // Worker authentication and security
    "WORKER_WEBSOCKET_AUTH_TOKEN": "REDIS_PASSWORD",

    // Custom ComfyUI Nodes Environment Variables (unprefixed - what the nodes expect)
    "AWS_ACCESS_KEY_ID": "STORAGE_PROVIDER_AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY_ENCODED": "STORAGE_PROVIDER_AWS_SECRET_ACCESS_KEY_ENCODED",
    "AWS_DEFAULT_REGION": "STORAGE_PROVIDER_AWS_DEFAULT_REGION",
    "GOOGLE_APPLICATION_CREDENTIALS": "STORAGE_PROVIDER_GOOGLE_APPLICATION_CREDENTIALS",
    "AZURE_STORAGE_ACCOUNT": "STORAGE_PROVIDER_AZURE_STORAGE_ACCOUNT", 
    "AZURE_STORAGE_KEY": "STORAGE_PROVIDER_AZURE_KEY",
    "CLOUD_PROVIDER": "STORAGE_PROVIDER_CURRENT_PROVIDER",
    "CLOUD_STORAGE_CONTAINER": "STORAGE_PROVIDER_CONTAINER",
    "CLOUD_CDN_URL": "STORAGE_PROVIDER_CDN_URL",
    "HF_TOKEN": "API_TOKENS_HF_TOKEN",
    "CIVITAI_TOKEN": "API_TOKENS_CIVITAI_TOKEN",
    "OPENAI_API_KEY": "API_TOKENS_OPENAI_API_KEY",
    "OLLAMA_HOST": "OLLAMA_HOST",
    "OLLAMA_PORT": "OLLAMA_PORT",
    "OLLAMA_DEFAULT_MODEL": "OLLAMA_DEFAULT_MODEL",
    "EMPROPS_DEBUG_LOGGING": "EMPROPS_DEBUG_LOGGING",
    "STATIC_MODELS": "STATIC_MODELS",
  },
  
  defaults: {}
};