/**
 * Machine Service Environment Interface
 * Container orchestration and service management
 */

export const MachineEnvInterface = {
  name: "machine",
  location: "apps/machine",
  
  required: {
    // Redis connection (used by both machine and workers)
    "HUB_REDIS_URL": "REDIS_URL",

    "EMPROPS_API_URL": "EMPROPS_API_URL",

    "WORKER_BUNDLE_MODE": "WORKER_BUNDLE_MODE",

    "UNIFIED_MACHINE_STATUS":"WORKER_UNIFIED_MACHINE_STATUS",

    "OPENAI_DEBUG":"OPENAI_DEBUG",

    "GPU_MODE": "MACHINE_GPU_MODE",

    "TELEMETRY_ENV":"TELEMETRY_DASH0_DATASET",

    "DASH0_DATASET":"TELEMETRY_DASH0_DATASET",
    "DASH0_TRACES_ENDPOINT": "TELEMETRY_DASH0_TRACES_ENDPOINT",
    "DASH0_METRICS_ENDPOINT": "TELEMETRY_DASH0_METRICS_ENDPOINT",

    "OTEL_ENABLED":"TELEMETRY_OTEL_ENABLED",
    "TELEMETRY_LOGS":"TELEMETRY_LOGS",
    "OTEL_COLLECTOR_TRACES_ENDPOINT":"TELEMETRY_OTEL_COLLECTOR_TRACES_ENDPOINT",
    "OTEL_COLLECTOR_METRICS_ENDPOINT":"TELEMETRY_OTEL_COLLECTOR_METRICS_ENDPOINT",
    "OTEL_SERVICE_NAME":"TELEMETRY_OTEL_SERVICE_NAME",
    "OTEL_SERVICE_VERSION":"TELEMETRY_OTEL_SERVICE_VERSION",

    "FLUENTD_HOST": "TELEMETRY_FLUENTD_HOST",
    "FLUENTD_PORT": "TELEMETRY_FLUENTD_PORT",
    "FLUENTD_SECURE": "TELEMETRY_FLUENTD_SECURE",

    "WORKER_COMFYUI_REMOTE_SECURE":"COMFYUI_REMOTE_SECURE",
    "DISABLE_ENV_ENCRYPTION":"MACHINE_DISABLE_ENV_ENCRYPTION"

  },
  
  optional: {
    
    // Machine monitoring and health
    "MACHINE_HEALTH_PORT": "MACHINE_HEALTH_PORT",
    "MACHINE_LOG_LEVEL": "MACHINE_LOG_LEVEL",
    "EXPOSE_PORTS":"MACHINE_EXPOSED_PORTS",

    // Worker authentication and security
    "WORKER_WEBSOCKET_AUTH_TOKEN": "REDIS_PASSWORD",

    // Remote ComfyUI
    "WORKER_COMFYUI_REMOTE_TIMEOUT_SECONDS": "COMFYUI_REMOTE_TIMEOUT_SECONDS",

    // Custom ComfyUI Nodes Environment Variables (unprefixed - what the nodes expect)

    "STATIC_MODELS": "STATIC_MODELS",

    "OPENAI_IMAGE_MODEL": "OPENAI_IMAGE_MODEL"
  },

  secret : {
    "AWS_ACCESS_KEY_ID": "STORAGE_PROVIDER_AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY_ENCODED": "STORAGE_PROVIDER_AWS_SECRET_ACCESS_KEY_ENCODED",
    "AWS_DEFAULT_REGION": "STORAGE_PROVIDER_AWS_DEFAULT_REGION",
    "AZURE_STORAGE_ACCOUNT": "STORAGE_PROVIDER_AZURE_STORAGE_ACCOUNT", 
    "AZURE_STORAGE_KEY": "STORAGE_PROVIDER_AZURE_KEY",
    "CLOUD_PROVIDER": "STORAGE_PROVIDER_CURRENT_SERVICE",
    "CLOUD_STORAGE_PROVIDER": "STORAGE_PROVIDER_CURRENT_SERVICE",
    "CLOUD_STORAGE_CONTAINER": "STORAGE_PROVIDER_CONTAINER",
    "CLOUD_CDN_URL": "STORAGE_PROVIDER_CDN_URL",
    "HF_TOKEN": "API_TOKENS_HF_TOKEN",
    "CIVITAI_TOKEN": "API_TOKENS_CIVITAI_TOKEN",
    "OPENAI_API_KEY": "OPENAI_API_KEY",
    "OLLAMA_HOST": "OLLAMA_HOST",
    "OLLAMA_PORT": "OLLAMA_PORT",
    "OLLAMA_DEFAULT_MODEL": "OLLAMA_DEFAULT_MODEL",
    "EMPROPS_DEBUG_LOGGING": "EMPROPS_DEBUG_LOGGING",
    "WORKER_COMFYUI_REMOTE_HOST":"COMFYUI_REMOTE_HOST",
    "WORKER_COMFYUI_REMOTE_PORT":"COMFYUI_REMOTE_PORT",
    "WORKER_COMFYUI_REMOTE_USERNAME":"COMFYUI_REMOTE_USER",
    "WORKER_COMFYUI_REMOTE_PASSWORD":"COMFYUI_REMOTE_PASS",
    "AUTH_TOKEN":"API_AUTH_TOKEN",
    "DASH0_API_KEY":"TELEMETRY_DASH0_API_KEY",
    "DASH0_ENDPOINT":"TELEMETRY_DASH0_ENDPOINT",
    "DASH0_TRACES_ENDPOINT":"TELEMETRY_DASH0_TRACES_ENDPOINT",
    "DASH0_METRICS_ENDPOINT":"TELEMETRY_DASH0_METRICS_ENDPOINT",
    "DASH0_LOGS_ENDPOINT":"TELEMETRY_DASH0_LOGS_ENDPOINT",
    "EMPROPS_API_AUTH": "EMPROPS_API_AUTH",
    "ENV_ENCRYPT_KEY": "MACHINE_ENV_ENCRYPTION_KEY"
  }, 
  
  defaults: {
    // Worker configuration (passed to workers)
    "WORKER_MAX_CONCURRENT_JOBS": "1",
    "WORKER_HEALTH_CHECK_INTERVAL": "30",

    "SERVICE_TYPE":"machine"
  }
};