/**
 * Webhook Service Environment Interface
 * Next.js web UI for monitoring job queues and workers
 */

export const WebhookServiceEnvInterface = {
  name: "webhook-service",
  location: "apps/webhook-service",
  
  required: {
    // Web server configuration
    "HUB_REDIS_URL": "REDIS_URL",
    "REDIS_URL": "REDIS_URL",
    "WEBHOOK_BASE_ID": "WEBHOOK_SERVICE_BASE_ID",
    "WEBHOOK_SERVICE_PORT": "WEBHOOK_SERVICE_PORT",
    "CORS_ORIGINS": "WEBHOOK_SERVICE_CORS_ORIGINS",
    "NEXT_PUBLIC_APP_URL": "WEBHOOK_SERVICE_URL",
    
    //TELEMETRY
    "TELEMETRY_ENV":"TELEMETRY_DASH0_DATASET",
    "OTEL_COLLECTOR_ENDPOINT": "TELEMETRY_OTEL_COLLECTOR_URL",
    "DASH0_DATASET":"TELEMETRY_DASH0_DATASET",
    "DASH0_TRACES_ENDPOINT": "TELEMETRY_DASH0_TRACES_ENDPOINT",
    "DASH0_METRICS_ENDPOINT": "TELEMETRY_DASH0_METRICS_ENDPOINT",
    "DASH0_ENDPOINT": "TELEMETRY_DASH0_ENDPOINT",
    "DASH0_LOGS_ENDPOINT": "TELEMETRY_DASH0_LOGS_ENDPOINT",
    "OTEL_ENABLED": "TELEMETRY_OTEL_ENABLED",
    "OTEL_COLLECTOR_TRACES_ENDPOINT": "TELEMETRY_OTEL_COLLECTOR_TRACES_ENDPOINT",
    "OTEL_COLLECTOR_METRICS_ENDPOINT": "TELEMETRY_OTEL_COLLECTOR_METRICS_ENDPOINT",
    "OTEL_SERVICE_NAME":"TELEMETRY_OTEL_SERVICE_NAME",
    "OTEL_SERVICE_VERSION":"TELEMETRY_OTEL_SERVICE_VERSION",
    
    // Required environment variables for OTEL client
    "SERVICE_NAME": "TELEMETRY_OTEL_SERVICE_NAME",
    "SERVICE_VERSION": "TELEMETRY_OTEL_SERVICE_VERSION",
    // Note: MACHINE_ID and WORKER_ID are set dynamically by machine/worker initialization code
    // Note: NODE_ENV not needed - use DASH0_DATASET for environment type
    

    "EMPROPS_API_URL": "EMPROPS_API_URL",
    "NODE_ENV": "API_NODE_ENV"
  },
  optional: {
  },
  secret: {
    "AUTH_TOKEN": "API_AUTH_TOKEN",
    "DASH0_AUTH_TOKEN": "TELEMETRY_DASH0_AUTH_TOKEN",
    "EMPROPS_API_AUTH": "EMPROPS_API_AUTH",
    "EMPROPS_API_KEY": "EMPROPS_API_KEY"
  }, 
  
  defaults: {
    "SERVICE_TYPE":"webhook",
    "LOG_TO_FILE": "true"
  }
};