# Docker Compose Example: Graceful Shutdown for Workers
# This demonstrates how to configure containers for proper shutdown handling

version: '3.8'

services:
  # Redis-Direct Worker with graceful shutdown
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      - NODE_ENV=production
      - WORKER_ID=basic-machine-local-worker-0
      - HUB_REDIS_URL=redis://redis:6379
      - MACHINE_ID=basic-machine-local
      - WORKER_SERVICES=comfyui,a1111
      - WORKER_GPU_MEMORY_GB=16
      - WORKER_RAM_GB=32
    # Graceful shutdown configuration
    stop_grace_period: 30s  # Give 30 seconds for graceful shutdown
    stop_signal: SIGTERM    # Send SIGTERM (default, but explicit)
    restart: unless-stopped
    depends_on:
      - redis
    
  # API Server
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    stop_grace_period: 15s
    stop_signal: SIGTERM
    restart: unless-stopped
    depends_on:
      - redis
  
  # Redis Database
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # Redis handles SIGTERM gracefully by default
    stop_grace_period: 10s
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:

# Key Configuration Points:
# 
# 1. stop_grace_period: How long Docker waits before sending SIGKILL
#    - Workers: 30s (time to finish current job and send shutdown event)
#    - API: 15s (time to close connections and update Redis)
#    - Redis: 10s (time to save data)
#
# 2. stop_signal: SIGTERM for graceful shutdown (default)
#
# 3. Environment Variables:
#    - NODE_ENV=production triggers "Docker container shutdown" reason
#    - MACHINE_ID helps identify which machine is shutting down
#
# 4. Restart Policy: unless-stopped prevents auto-restart during manual shutdown
#
# Usage:
#   docker-compose -f docker-shutdown-example.yml up -d
#   docker-compose -f docker-shutdown-example.yml stop worker  # Graceful shutdown
#   docker-compose -f docker-shutdown-example.yml logs -f     # Watch shutdown events