# Docker Compose configuration for Redis-Direct Architecture
# Phase 1C - Lightweight API with direct Redis polling workers
#
# CRITICAL WORKER ARCHITECTURE:
# - Each worker processes EXACTLY ONE job at a time (single-threaded)
# - Multi-GPU machines run MULTIPLE workers (one per GPU)
# - Each worker connects to its own service port (worker0→8188, worker1→8189, etc.)
# - A 4x GPU machine = 4 separate workers = 4 separate service instances
# - NEVER set WORKER_MAX_CONCURRENT_JOBS > 1

services:
  # Lightweight API Server (replaces hub orchestration)
  # Now connects to Railway Redis with Functions support
  api:
    container_name: emp-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3001:3001"  # HTTP + WebSocket API
    environment:
      - NODE_ENV=production
      - API_PORT=3001
      - REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - CORS_ORIGINS=*
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
      - REDIS_FUNCTIONS_ENABLED=true
    networks:
      - emp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - one-worker
      - all-workers

  # Redis-Direct Worker 1 - Simulation connector
  worker1:
    container_name: emp-worker1
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_MACHINE_ID:server-1
      - WORKER_ID=worker1-direct
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=30
      # Simulation connector config
      - WORKER_SIMULATION_PROCESSING_TIME=5
      - WORKER_SIMULATION_STEPS=25
      # Hardware specs
      - WORKER_GPU_COUNT=1
      - WORKER_GPU_MEMORY_GB=8
      - WORKER_GPU_MODEL=Simulation
      - WORKER_MACHINE_ID=dev-machine-1
      - WORKER_RAM_GB=16
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - one-worker

  worker2:
    container_name: emp-worker2
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_MACHINE_ID:server-1
      - WORKER_ID=worker2-direct
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=30
      # Simulation connector config (faster)
      - WORKER_SIMULATION_PROCESSING_TIME=3
      - WORKER_SIMULATION_STEPS=15
      # Hardware specs
      - WORKER_GPU_COUNT=1
      - WORKER_GPU_MEMORY_GB=8
      - WORKER_GPU_MODEL=Simulation
      - WORKER_MACHINE_ID=dev-machine-2
      - WORKER_RAM_GB=16
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    profiles:
      - all-workers


  # Redis-Direct Worker 3 - ComfyUI + Simulation
  worker3:
    container_name: emp-worker3
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_MACHINE_ID:server-1
      - WORKER_ID=worker3-comfyui
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=comfyui,simulation
      - WORKER_CONNECTORS=comfyui,simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=60
      # ComfyUI connector config
      - WORKER_COMFYUI_HOST=${COMFYUI_HOST:-host.docker.internal}
      - WORKER_COMFYUI_PORT=${COMFYUI_PORT:-8188}
      - WORKER_COMFYUI_USERNAME=${COMFYUI_USERNAME:-}
      - WORKER_COMFYUI_PASSWORD=${COMFYUI_PASSWORD:-}
      - WORKER_COMFYUI_USE_BASIC_AUTH=${COMFYUI_USE_BASIC_AUTH:-false}
      # Simulation connector config
      - WORKER_SIMULATION_PROCESSING_TIME=10
      - WORKER_SIMULATION_STEPS=5
      # Hardware specs (GPU worker)
      - WORKER_GPU_COUNT=1
      - WORKER_GPU_MEMORY_GB=24
      - WORKER_GPU_MODEL=RTX 4090
      - WORKER_MACHINE_ID=gpu-machine-1
      - WORKER_RAM_GB=64
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers
  # Redis-Direct Worker 4 - Multiple instances (scale test)
  worker4:
    container_name: emp-worker4
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_MACHINE_ID:server-1
      - WORKER_ID=worker4-scale
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=500  # Faster polling for scale test
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=15
      # Simulation connector config (very fast)
      - WORKER_SIMULATION_PROCESSING_TIME=1
      - WORKER_SIMULATION_STEPS=10
      # Hardware specs
      - WORKER_GPU_COUNT=0
      - WORKER_MACHINE_ID=scale-machine
      - WORKER_RAM_GB=8
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers
  worker5:
    container_name: emp-worker5
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker5-scale
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=500  # Faster polling for scale test
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=15
      # Simulation connector config (very fast)
      - WORKER_SIMULATION_PROCESSING_TIME=1
      - WORKER_SIMULATION_STEPS=10
      # Hardware specs
      - WORKER_GPU_COUNT=0
      - WORKER_MACHINE_ID=scale-machine
      - WORKER_RAM_GB=8
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers
  worker6:
    container_name: emp-worker6
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker6-scale
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=500  # Faster polling for scale test
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=15
      # Simulation connector config (very fast)
      - WORKER_SIMULATION_PROCESSING_TIME=1
      - WORKER_SIMULATION_STEPS=10
      # Hardware specs
      - WORKER_GPU_COUNT=0
      - WORKER_MACHINE_ID=scale-machine
      - WORKER_RAM_GB=8
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers
  worker7:
    container_name: emp-worker7
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker7-scale
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=500  # Faster polling for scale test
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=15
      # Simulation connector config (very fast)
      - WORKER_SIMULATION_PROCESSING_TIME=1
      - WORKER_SIMULATION_STEPS=10
      # Hardware specs
      - WORKER_GPU_COUNT=0
      - WORKER_MACHINE_ID=scale-machine
      - WORKER_RAM_GB=8
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers
  worker8:
    container_name: emp-worker8
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker8-scale
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=500  # Faster polling for scale test
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=15
      # Simulation connector config (very fast)
      - WORKER_SIMULATION_PROCESSING_TIME=1
      - WORKER_SIMULATION_STEPS=10
      # Hardware specs
      - WORKER_GPU_COUNT=0
      - WORKER_MACHINE_ID=scale-machine
      - WORKER_RAM_GB=8
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers
  worker9:
    container_name: emp-worker9
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker9-scale
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=500  # Faster polling for scale test
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=15
      # Simulation connector config (very fast)
      - WORKER_SIMULATION_PROCESSING_TIME=1
      - WORKER_SIMULATION_STEPS=10
      # Hardware specs
      - WORKER_GPU_COUNT=0
      - WORKER_MACHINE_ID=scale-machine
      - WORKER_RAM_GB=8
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers

  worker10:
    container_name: emp-worker10
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker10-direct
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=30
      # Simulation connector config
      - WORKER_SIMULATION_PROCESSING_TIME=5
      - WORKER_SIMULATION_STEPS=25
      # Hardware specs
      - WORKER_GPU_COUNT=1
      - WORKER_GPU_MEMORY_GB=8
      - WORKER_GPU_MODEL=Simulation
      - WORKER_MACHINE_ID=dev-machine-3
      - WORKER_RAM_GB=16
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers
    # Redis-Direct Worker 2 - Simulation connector (faster)
  worker11:
    container_name: emp-worker11
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker11-direct
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=30
      # Simulation connector config (faster)
      - WORKER_SIMULATION_PROCESSING_TIME=3
      - WORKER_SIMULATION_STEPS=15
      # Hardware specs
      - WORKER_GPU_COUNT=1
      - WORKER_GPU_MEMORY_GB=8
      - WORKER_GPU_MODEL=Simulation
      - WORKER_MACHINE_ID=dev-machine-4
      - WORKER_RAM_GB=16
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - all-workers


  # Note: Redis is now hosted on Railway with Functions support
  # Access Railway Redis dashboard for monitoring instead of local Redis Commander

  # ===============================
  # CAPABILITY TEST WORKERS PROFILE
  # ===============================
  
  # Worker with only simulation capability
  worker-sim-only:
    container_name: emp-worker-sim-only
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker-sim-only
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=60
      # Simulation config
      - WORKER_SIMULATION_PROCESSING_TIME=5
      - WORKER_SIMULATION_STEPS=3
      # Hardware specs (low-end)
      - WORKER_GPU_COUNT=0
      - WORKER_GPU_MEMORY_GB=0
      - WORKER_RAM_GB=8
      - WORKER_MACHINE_ID=cpu-only-machine
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - capability-test

  # Worker with ComfyUI simulation capability  
  worker-comfy-sim:
    container_name: emp-worker-comfy-sim
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker-comfy-sim
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=comfyui-sim
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=60
      # Simulation config (slower for ComfyUI)
      - WORKER_SIMULATION_PROCESSING_TIME=15
      - WORKER_SIMULATION_STEPS=5
      # Hardware specs (GPU enabled)
      - WORKER_GPU_COUNT=1
      - WORKER_GPU_MEMORY_GB=16
      - WORKER_GPU_MODEL=RTX 3080
      - WORKER_RAM_GB=32
      - WORKER_MACHINE_ID=gpu-machine-2
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - capability-test

  # Worker with A1111 simulation capability
  worker-a1111-sim:
    container_name: emp-worker-a1111-sim
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker-a1111-sim
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=a1111-sim
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=60
      # Simulation config (faster for A1111)
      - WORKER_SIMULATION_PROCESSING_TIME=8
      - WORKER_SIMULATION_STEPS=4
      # Hardware specs (GPU enabled)
      - WORKER_GPU_COUNT=1
      - WORKER_GPU_MEMORY_GB=24
      - WORKER_GPU_MODEL=RTX 4090
      - WORKER_RAM_GB=64
      - WORKER_MACHINE_ID=gpu-machine-3
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - capability-test

  # Worker with multiple capabilities (ComfyUI + A1111 sim)
  worker-multi-sim:
    container_name: emp-worker-multi-sim
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker-multi-sim
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=comfyui-sim,a1111-sim,simulation
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=60
      # Simulation config (balanced)
      - WORKER_SIMULATION_PROCESSING_TIME=10
      - WORKER_SIMULATION_STEPS=4
      # Hardware specs (high-end GPU)
      - WORKER_GPU_COUNT=2
      - WORKER_GPU_MEMORY_GB=48
      - WORKER_GPU_MODEL=RTX A6000
      - WORKER_RAM_GB=128
      - WORKER_MACHINE_ID=gpu-machine-4
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - capability-test

  # Worker with low GPU memory (can't handle large models)
  worker-low-gpu:
    container_name: emp-worker-low-gpu
    build:
      context: .
      dockerfile: Dockerfile.worker-direct
    environment:
      - NODE_ENV=production
      - WORKER_ID=worker-low-gpu
      - HUB_REDIS_URL=redis://default:JQSoNVpIPsuaDQYicNvocglialxPrTjj@ballast.proxy.rlwy.net:30645
      - WORKER_SERVICES=comfyui-sim,a1111-sim
      - WORKER_CONNECTORS=simulation
      - WORKER_POLL_INTERVAL_MS=1000
      - WORKER_HEARTBEAT_INTERVAL_MS=30000
      - WORKER_JOB_TIMEOUT_MINUTES=60
      # Simulation config
      - WORKER_SIMULATION_PROCESSING_TIME=20
      - WORKER_SIMULATION_STEPS=3
      # Hardware specs (low GPU memory)
      - WORKER_GPU_COUNT=1
      - WORKER_GPU_MEMORY_GB=8
      - WORKER_GPU_MODEL=RTX 3060
      - WORKER_RAM_GB=16
      - WORKER_MACHINE_ID=gpu-machine-5
      - LOG_LEVEL=info
      - DISABLE_FILE_LOGGING=true
    networks:
      - emp-network
    restart: unless-stopped
    profiles:
      - capability-test

networks:
  emp-network:
    driver: bridge

# No volumes needed - Redis is hosted on Railway