[variables]
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_NPM_VERSION = "10"

[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build", "pnpm --filter=api build"]

[start]
cmd = "pnpm start"