[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm railway:start"
restartPolicyType = "always"

[env]
NODE_ENV = "production"

# Watch for changes in API and core packages
watchPatterns = [
  "apps/api/**",
  "packages/core/**",
  "package.json",
  "pnpm-lock.yaml"
]