[build]
builder = "dockerfile"
dockerfile = "Dockerfile.redis"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[[services]]
name = "redis-functions"
dockerfile = "Dockerfile.redis"

[services.redis-functions.variables]
REDIS_ARGS = "--enable-module-command"