# Docker Compose for Fluent Bit testing
services:
  fluent-bit:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: fluent-bit-sidecar
    
    environment:
      # Machine and worker identification
      - MACHINE_ID=railway-test
      - WORKER_ID=worker-001
      - SERVICE_TYPE=comfyui
      
      # Fluentd destination - use host.docker.internal 
      - FLUENTD_HOST=host.docker.internal
    
    # Expose Fluent Bit HTTP input port
    ports:
      - "9880:9880"
    
    restart: unless-stopped
    
    # Optional: Mount logs directory if collecting from files
    # volumes:
    #   - ./logs:/var/log/worker:ro