services:
  base-machine: &base-machine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUST: ${CACHE_BUST:-1}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY_ENCODED: ${AWS_SECRET_ACCESS_KEY_ENCODED}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        HF_TOKEN: ${HF_TOKEN}
        CIVITAI_TOKEN: ${CIVITAI_TOKEN}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    image: ${MACHINE_IMAGE:-base-machine:latest}
    platform: linux/amd64
    container_name: ${MACHINE_CONTAINER_NAME:-base-machine}
    hostname: ${MACHINE_CONTAINER_NAME:-base-machine}
    profiles:
      - never-run-directly
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  comfyui-remote:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        WORKERS: comfyui-remote:1
        MACHINE_ID: comfyui-remote
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:comfyui-remote
    platform: linux/amd64
    container_name: comfyui-remote-${CURRENT_ENV}
    hostname: comfyui-remote
    profiles:
      - comfyui-remote
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
    ports:
      - ${EXPOSE_PORTS:-9090}:9090
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
      target: comfyui
      args:
        WORKER_SPEC: comfyui:1
        WORKERS: comfyui:1
        MACHINE_ID: comfyui
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:comfyui
    platform: linux/amd64
    container_name: comfyui-${CURRENT_ENV}
    hostname: comfyui
    profiles:
      - comfyui
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
    ports:
      - ${EXPOSE_PORTS:-9090}:9090
      - '3188:8188'
  openai:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: openai:5
        WORKERS: openai:5
        MACHINE_ID: openai
        CACHE_BUST: ${CACHE_BUST:-1}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        OPENAI_IMAGE_MODEL: ${OPENAI_IMAGE_MODEL}
        CLOUD_STORAGE_PROVIDER: ${CLOUD_STORAGE_PROVIDER}
    image: emprops/machine:openai
    platform: linux/amd64
    container_name: openai-${CURRENT_ENV}
    hostname: openai
    profiles:
      - openai
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
    ports:
      - ${EXPOSE_PORTS:-9090}:9090
  simulation:
    build:
      context: .
      dockerfile: Dockerfile
      target: simulation
      args:
        WORKER_SPEC: simulation:5
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:simulation
    platform: linux/amd64
    container_name: simulation-${ENV:-local}
    hostname: simulation
    profiles:
      - simulation
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: simulation:5
      MACHINE_ID: simulation
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  openai-text:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: openai-text:5
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:openai-text
    platform: linux/amd64
    container_name: openai-text-${ENV:-local}
    hostname: openai-text
    profiles:
      - openai-text
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: openai-text:5
      MACHINE_ID: openai-text
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  sim:
    build:
      context: .
      dockerfile: Dockerfile
      target: simulation
      args:
        WORKER_SPEC: simulation:10
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:sim
    platform: linux/amd64
    container_name: sim-${ENV:-local}
    hostname: sim
    profiles:
      - sim
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: simulation:10
      MACHINE_ID: sim
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  comfyui-remote-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        WORKERS: comfyui-remote:1
        MACHINE_ID: comfyui-remote-test
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:comfyui-remote-test
    platform: linux/amd64
    container_name: comfyui-remote-test-${ENV:-local}
    hostname: comfyui-remote-test
    profiles:
      - comfyui-remote-test
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: production
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  sim-local:
    build:
      context: .
      dockerfile: Dockerfile
      target: simulation
      args:
        WORKER_SPEC: simulation:10
        WORKERS: simulation:10
        MACHINE_ID: sim-local
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:sim-local
    platform: linux/amd64
    container_name: sim-local-${CURRENT_ENV}
    hostname: sim-local
    profiles:
      - sim-local
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
    ports:
      - ${EXPOSE_PORTS:-9090}:9090
      - '3188:8188'
      - '3189:8189'
      - '3190:8190'
      - '3191:8191'
      - '3192:8192'
      - '3193:8193'
      - '3194:8194'
      - '3195:8195'
      - '3196:8196'
      - '3197:8197'
  comfyui-remote-local:
    <<: *base-machine
    profiles:
      - comfyui-remote-local
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        WORKERS: comfyui-remote:1
        MACHINE_ID: comfyui-remote-local
        CACHE_BUST: ${CACHE_BUST:-1}
    container_name: comfyui-remote-local-${CURRENT_ENV}
    hostname: comfyui-remote-local
    ports:
      - ${EXPOSE_PORTS:-9090}:9090
    image: emprops/machine:comfyui-remote-local
networks:
  default:
    name: emp-job-queue
volumes: {}
