# Docker Compose override for local development
# This file mounts the local worker build to avoid downloading from GitHub
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  basic-machine:
    volumes:
      # Mount bundled worker (single file with all dependencies)
      # Run: ./scripts/bundle-worker.sh to create this
      - ../../worker/bundled:/workspace/worker-bundled:ro
    
    environment:
      # Override to use local bundled worker
      - WORKER_LOCAL_PATH=/workspace/worker-bundled