services:
  base-machine: &base-machine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUST: ${CACHE_BUST:-1}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY_ENCODED: ${AWS_SECRET_ACCESS_KEY_ENCODED}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        HF_TOKEN: ${HF_TOKEN}
        CIVITAI_TOKEN: ${CIVITAI_TOKEN}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    image: ${MACHINE_IMAGE:-base-machine:latest}
    platform: linux/amd64
    container_name: ${MACHINE_CONTAINER_NAME:-base-machine}
    hostname: ${MACHINE_CONTAINER_NAME:-base-machine}
    profiles:
      - never-run-directly
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  comfyui-remote:
    <<: *base-machine
    profiles:
      - comfyui-remote
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        WORKERS: comfyui-remote:1
        MACHINE_ID: comfyui-remote-${CURRENT_ENV}
        CACHE_BUST: ${CACHE_BUST:-1}
    container_name: comfyui-remote-${CURRENT_ENV}
    hostname: comfyui-remote-${CURRENT_ENV}
    image: emprops/machine:comfyui-remote
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
      target: comfyui
      args:
        WORKER_SPEC: comfyui:1
        WORKERS: comfyui:1
        MACHINE_ID: comfyui-${CURRENT_ENV}
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:comfyui
    platform: linux/amd64
    container_name: comfyui-${CURRENT_ENV}
    hostname: comfyui-${CURRENT_ENV}
    profiles:
      - comfyui
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  openai:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: openai:5
        WORKERS: openai:5
        MACHINE_ID: openai-${CURRENT_ENV}
        CACHE_BUST: ${CACHE_BUST:-1}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        OPENAI_IMAGE_MODEL: ${OPENAI_IMAGE_MODEL}
        CLOUD_STORAGE_PROVIDER: ${CLOUD_STORAGE_PROVIDER}
    image: emprops/machine:openai
    platform: linux/amd64
    container_name: openai-${CURRENT_ENV}
    hostname: openai-${CURRENT_ENV}
    profiles:
      - openai
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  simulation:
    build:
      context: .
      dockerfile: Dockerfile
      target: simulation
      args:
        WORKER_SPEC: simulation:5
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:simulation
    platform: linux/amd64
    container_name: simulation-${ENV:-local}
    hostname: simulation-${ENV:-local}
    profiles:
      - simulation
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: simulation:5
      MACHINE_ID: simulation-${ENV:-local}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  openai-text:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: openai-text:5
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:openai-text
    platform: linux/amd64
    container_name: openai-text-${ENV:-local}
    hostname: openai-text-${ENV:-local}
    profiles:
      - openai-text
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: openai-text:5
      MACHINE_ID: openai-text-${ENV:-local}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  sim:
    build:
      context: .
      dockerfile: Dockerfile
      target: simulation
      args:
        WORKER_SPEC: simulation:10
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:sim
    platform: linux/amd64
    container_name: sim-${ENV:-local}
    hostname: sim-${ENV:-local}
    profiles:
      - sim
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: simulation:10
      MACHINE_ID: sim-${ENV:-local}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  comfyui-remote-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        WORKERS: comfyui-remote:1
        MACHINE_ID: comfyui-remote-test-${ENV:-local}
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:comfyui-remote-test
    platform: linux/amd64
    container_name: comfyui-remote-test-${ENV:-local}
    hostname: comfyui-remote-test-${ENV:-local}
    profiles:
      - comfyui-remote-test
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: production
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  test-current-env:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        WORKERS: comfyui-remote:1
        MACHINE_ID: test-current-env-${ENV:-local}
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:test-current-env
    platform: linux/amd64
    container_name: test-current-env-${ENV:-local}
    hostname: test-current-env-${ENV:-local}
    profiles:
      - test-current-env
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: production
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  test-env-fix:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        WORKERS: comfyui-remote:1
        MACHINE_ID: test-env-fix-${ENV:-local}
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:test-env-fix
    platform: linux/amd64
    container_name: test-env-fix-${ENV:-local}
    hostname: test-env-fix-${ENV:-local}
    profiles:
      - test-env-fix
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: production
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  final-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        WORKERS: comfyui-remote:1
        MACHINE_ID: final-test-${ENV:-local}
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:final-test
    platform: linux/amd64
    container_name: final-test-${ENV:-local}
    hostname: final-test-${ENV:-local}
    profiles:
      - final-test
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: ${CURRENT_ENV:-local}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
networks:
  default:
    name: emp-job-queue
volumes: {}
