services:
  base-machine: &base-machine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUST: ${CACHE_BUST:-1}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY_ENCODED: ${AWS_SECRET_ACCESS_KEY_ENCODED}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        HF_TOKEN: ${HF_TOKEN}
        CIVITAI_TOKEN: ${CIVITAI_TOKEN}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    image: ${MACHINE_IMAGE:-base-machine:latest}
    platform: linux/amd64
    container_name: ${MACHINE_CONTAINER_NAME:-base-machine}
    hostname: ${MACHINE_CONTAINER_NAME:-base-machine}
    profiles:
      - never-run-directly
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: production
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  comfyui-remote:
    <<: *base-machine
    profiles:
      - comfyui-remote
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        CACHE_BUST: ${CACHE_BUST:-1}
    environment:
      WORKERS: comfyui-remote:1
      MACHINE_ID: comfyui-remote-${ENV:-local}
    container_name: comfyui-remote-${ENV:-local}
    hostname: comfyui-remote-${ENV:-local}
    image: emprops/machine:comfyui-remote
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
      target: comfyui
      args:
        WORKER_SPEC: comfyui:1
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:comfyui
    platform: linux/amd64
    container_name: comfyui-${ENV:-local}
    hostname: comfyui-${ENV:-local}
    profiles:
      - comfyui
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: comfyui:1
      MACHINE_ID: comfyui-${ENV:-local}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  openai:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: openai:5
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:openai
    platform: linux/amd64
    container_name: openai-${ENV:-local}
    hostname: openai-${ENV:-local}
    profiles:
      - openai
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: openai:5
      MACHINE_ID: openai-${ENV:-local}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_IMAGE_MODEL: ${OPENAI_IMAGE_MODEL}
      CLOUD_STORAGE_PROVIDER: ${CLOUD_STORAGE_PROVIDER}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  simulation:
    build:
      context: .
      dockerfile: Dockerfile
      target: simulation
      args:
        WORKER_SPEC: simulation:5
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:simulation
    platform: linux/amd64
    container_name: simulation-${ENV:-local}
    hostname: simulation-${ENV:-local}
    profiles:
      - simulation
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: simulation:5
      MACHINE_ID: simulation-${ENV:-local}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  openai-text:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: openai-text:5
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:openai-text
    platform: linux/amd64
    container_name: openai-text-${ENV:-local}
    hostname: openai-text-${ENV:-local}
    profiles:
      - openai-text
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: openai-text:5
      MACHINE_ID: openai-text-${ENV:-local}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  sim:
    build:
      context: .
      dockerfile: Dockerfile
      target: simulation
      args:
        WORKER_SPEC: simulation:10
        CACHE_BUST: ${CACHE_BUST:-1}
    image: emprops/machine:sim
    platform: linux/amd64
    container_name: sim-${ENV:-local}
    hostname: sim-${ENV:-local}
    profiles:
      - sim
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      WORKERS: simulation:10
      MACHINE_ID: sim-${ENV:-local}
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
networks:
  default:
    name: emp-job-queue
volumes: {}
