services:
  base-machine: &base-machine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUST: ${CACHE_BUST:-1}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY_ENCODED: ${AWS_SECRET_ACCESS_KEY_ENCODED}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        HF_TOKEN: ${HF_TOKEN}
        CIVITAI_TOKEN: ${CIVITAI_TOKEN}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    image: ${MACHINE_IMAGE:-base-machine:latest}
    platform: linux/amd64
    container_name: ${MACHINE_CONTAINER_NAME:-base-machine}
    hostname: ${MACHINE_CONTAINER_NAME:-base-machine}
    profiles:
      - never-run-directly
    restart: 'no'
    stop_grace_period: 2s
    stop_signal: SIGTERM
    env_file:
      - .env.secret
    environment:
      NODE_ENV: production
      ENV: local
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    working_dir: /workspace
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-8G}
        reservations:
          memory: ${MEMORY_RESERVATION:-2G}
  comfyui-remote:
    <<: *base-machine
    profiles:
      - comfyui-remote
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        WORKER_SPEC: comfyui-remote:1
        CACHE_BUST: ${CACHE_BUST:-1}
    environment:
      WORKERS: comfyui-remote:1
    container_name: comfyui-remote-${ENV:-local}
    hostname: comfyui-remote-${ENV:-local}
    image: emprops/machine:comfyui-remote
networks:
  default:
    name: emp-job-queue
volumes: {}
